# Generated by Django 3.0.5 on 2020-07-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='name')),
                ('text', models.CharField(default='', max_length=3000, verbose_name='text')),
                ('href', models.CharField(default='', max_length=100, verbose_name='href')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
