# Generated by Django 3.0.5 on 2020-07-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200719_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.CharField(default='', max_length=100000, verbose_name='text'),
        ),
    ]
